using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using SPT.Reflection.Patching;
using EFT;
using SPTQuestingBots.Controllers;

namespace SPTQuestingBots.Patches
{
    public class IsFollowerSuitableForBossPatch : ModulePatch
    {
        protected override MethodBase GetTargetMethod()
        {
            return typeof(BotBoss).GetMethod("OfferSelf", BindingFlags.Public | BindingFlags.Instance);
        }

        [PatchPrefix]
        private static bool PatchPrefix(ref bool __result, BotBoss __instance, BotOwner offer)
        {
            // EFT sometimes instructs bots ask themselves to be followers of themselves. I guess they're really lonely, so we'll allow it.  
            if (__instance.Owner.Profile.Id == offer.Profile.Id)
            {
                return true;
            }

            // Always allow Zryachiy's followers to join existing groups because they respawn if any are killed
            // TODO: Is this redundant?
            if (offer.Profile.Info.Settings.Role == WildSpawnType.followerZryachiy)
            {
                return true;
            }

            //Controllers.LoggingController.LogInfo("Checking if " + offer.GetText() + " can be a follower for " + __instance.Owner.GetText() + "...");

            // Always let bots join bosses
            // TODO: Is this redundant?
            if (BotRegistrationManager.IsBotABoss(__instance.Owner))
            {
                return true;
            }

            IEnumerable<BotOwner> bossGroupMembers = Enumerable.Empty<BotOwner>();
            IEnumerable<BotOwner> offerGroupMembers = Enumerable.Empty<BotOwner>();

            // Try to get the bots' group members from the bot groups generated by this mod
            if (Components.Spawning.BotGenerator.TryGetBotGroupFromAnyGenerator(__instance.Owner, out Models.BotSpawnInfo botSpawnInfo))
            {
                bossGroupMembers = botSpawnInfo.SpawnedBots;
            }
            if (Components.Spawning.BotGenerator.TryGetBotGroupFromAnyGenerator(offer, out botSpawnInfo))
            {
                offerGroupMembers = botSpawnInfo.SpawnedBots;
            }

            //Controllers.LoggingController.LogInfo(__instance.Owner.GetText() + "'s group contains: " + string.Join(",", groupMembers.Select(m => m.GetText())));

            // If neither the boss nor the offer were spawned in the bot groups generated by this mod, run the EFT code
            if (!bossGroupMembers.Any() && !offerGroupMembers.Any())
            {
                return true;
            }

            // Allow the offer to join the boss's group if it spawned in that group
            if (bossGroupMembers.Any(m => m.Id == offer.Id))
            {
                return true;
            }

            Controllers.LoggingController.LogInfo("Preventing " + offer.GetText() + " from becoming a follower for " + __instance.Owner.GetText());

            __result = false;
            return false;
        }
    }
}
